import { axisInstance } from "@/lib/constants";
import { objectToQueryString } from "@/lib/utils";
import { WOSLineType, WOSMasterType } from "@/type/wos/wos-types";

export type WOSMaterServiceParams = {
  from_date?: string;
  to_date?: string;
  customer_code?: string;
  station_code?: string;
};

export async function wosMasterService(params: WOSMaterServiceParams) {
  const queryString = objectToQueryString(params);
  const res = await axisInstance.get<WOSMasterType[]>(
    "wosmaster" + queryString,
  );
  return res.data;
}

export type WOSLineServiceParams = {
  wosserial: number;
};

export async function wosLineService(params: WOSLineServiceParams) {
  const res = await axisInstance.get<WOSLineType[]>(
    `wosline?wosserial=${params.wosserial}`,
  );
  return res.data;
}

// const d = [
//   {
//     WOSSerial: 24,
//     WOSLineSerial: 1,
//     ItemCode: "N0552-5252105",
//     ItemDesc: "COMPASS MAGNETIC",
//     ItemDeno: "NO",
//     SOS: "MO",
//     AuthorisedQty: 1.0,
//     ReceivedQty: 1.0,
//     BalanceQty: 0.0,
//     ReviewedQty: 1.0,
//     VettedQty: 1.0,
//     RecommendedQty: 1.0,
//     DateFromWhichHeld: null,
//     AuthorityRef: "WOS-24",
//     AuthorityDate: "2026-01-29T00:00:00",
//     Justification: "Initial issue",
//     Price: null,
//     TotalCost: null,
//     Remarks: null,
//     ClosedBy: null,
//     DateTimeClosed: null,
//   },
//   {
//     WOSSerial: 24,
//     WOSLineSerial: 2,
//     ItemCode: "N0565-4218115",
//     ItemDesc: "PAINT SPRAYING EQUIPMENT COMPLETE",
//     ItemDeno: "NO",
//     SOS: "MO",
//     AuthorisedQty: 2.0,
//     ReceivedQty: 2.0,
//     BalanceQty: 0.0,
//     ReviewedQty: 2.0,
//     VettedQty: 2.0,
//     RecommendedQty: 2.0,
//     DateFromWhichHeld: null,
//     AuthorityRef: "WOS-24",
//     AuthorityDate: "2026-01-29T00:00:00",
//     Justification: "Initial issue",
//     Price: null,
//     TotalCost: null,
//     Remarks: null,
//     ClosedBy: null,
//     DateTimeClosed: null,
//   },
//   {
//     WOSSerial: 24,
//     WOSLineSerial: 3,
//     ItemCode: "N3410-P061834",
//     ItemDesc: "PROTECTIVE GOGGLES",
//     ItemDeno: "NO",
//     SOS: "MO",
//     AuthorisedQty: 14.0,
//     ReceivedQty: 14.0,
//     BalanceQty: 0.0,
//     ReviewedQty: 14.0,
//     VettedQty: 14.0,
//     RecommendedQty: 14.0,
//     DateFromWhichHeld: null,
//     AuthorityRef: "WOS-24",
//     AuthorityDate: "2026-01-29T00:00:00",
//     Justification: "Initial issue",
//     Price: null,
//     TotalCost: null,
//     Remarks: null,
//     ClosedBy: null,
//     DateTimeClosed: null,
//   },
//   {
//     WOSSerial: 24,
//     WOSLineSerial: 4,
//     ItemCode: "N4220-000001",
//     ItemDesc: "LIFE BOUY PLASTIC",
//     ItemDeno: "NO",
//     SOS: "MO",
//     AuthorisedQty: 10.0,
//     ReceivedQty: 10.0,
//     BalanceQty: 0.0,
//     ReviewedQty: 10.0,
//     VettedQty: 10.0,
//     RecommendedQty: 10.0,
//     DateFromWhichHeld: null,
//     AuthorityRef: "WOS-24",
//     AuthorityDate: "2026-01-29T00:00:00",
//     Justification: "Initial issue",
//     Price: null,
//     TotalCost: null,
//     Remarks: null,
//     ClosedBy: null,
//     DateTimeClosed: null,
//   },
//   {
//     WOSSerial: 24,
//     WOSLineSerial: 5,
//     ItemCode: "N5120-P060019",
//     ItemDesc: '7" ANGLE GRINDER',
//     ItemDeno: "NO",
//     SOS: "MO",
//     AuthorisedQty: 2.0,
//     ReceivedQty: 2.0,
//     BalanceQty: 0.0,
//     ReviewedQty: 2.0,
//     VettedQty: 2.0,
//     RecommendedQty: 2.0,
//     DateFromWhichHeld: null,
//     AuthorityRef: "WOS-24",
//     AuthorityDate: "2026-01-29T00:00:00",
//     Justification: "Initial issue",
//     Price: null,
//     TotalCost: null,
//     Remarks: null,
//     ClosedBy: null,
//     DateTimeClosed: null,
//   },
//   {
//     WOSSerial: 24,
//     WOSLineSerial: 6,
//     ItemCode: "N5805-P061575",
//     ItemDesc: "CORDLESS TELEPHONE DOUBLE LINE",
//     ItemDeno: "NO",
//     SOS: "MO",
//     AuthorisedQty: 3.0,
//     ReceivedQty: 3.0,
//     BalanceQty: 0.0,
//     ReviewedQty: 3.0,
//     VettedQty: 3.0,
//     RecommendedQty: 3.0,
//     DateFromWhichHeld: null,
//     AuthorityRef: "WOS-24",
//     AuthorityDate: "2026-01-29T00:00:00",
//     Justification: "Initial issue",
//     Price: null,
//     TotalCost: null,
//     Remarks: null,
//     ClosedBy: null,
//     DateTimeClosed: null,
//   },
//   {
//     WOSSerial: 24,
//     WOSLineSerial: 7,
//     ItemCode: "N5805-P061577",
//     ItemDesc: "FAX MACHINE",
//     ItemDeno: "NO",
//     SOS: "MO",
//     AuthorisedQty: 1.0,
//     ReceivedQty: 1.0,
//     BalanceQty: 0.0,
//     ReviewedQty: 1.0,
//     VettedQty: 1.0,
//     RecommendedQty: 1.0,
//     DateFromWhichHeld: null,
//     AuthorityRef: "WOS-24",
//     AuthorityDate: "2026-01-29T00:00:00",
//     Justification: "Initial issue",
//     Price: null,
//     TotalCost: null,
//     Remarks: null,
//     ClosedBy: null,
//     DateTimeClosed: null,
//   },
//   {
//     WOSSerial: 24,
//     WOSLineSerial: 8,
//     ItemCode: "N5855-000624",
//     ItemDesc: "NIGHT VISION GOGGLE",
//     ItemDeno: "NO",
//     SOS: "MO",
//     AuthorisedQty: 4.0,
//     ReceivedQty: 4.0,
//     BalanceQty: 0.0,
//     ReviewedQty: 4.0,
//     VettedQty: 4.0,
//     RecommendedQty: 4.0,
//     DateFromWhichHeld: null,
//     AuthorityRef: "WOS-24",
//     AuthorityDate: "2026-01-29T00:00:00",
//     Justification: "Initial issue",
//     Price: null,
//     TotalCost: null,
//     Remarks: null,
//     ClosedBy: null,
//     DateTimeClosed: null,
//   },
//   {
//     WOSSerial: 24,
//     WOSLineSerial: 9,
//     ItemCode: "N6605-P060221",
//     ItemDesc: "PASSIVE NIGHT VISION BINOCULAR (L/W)",
//     ItemDeno: "NO",
//     SOS: "MO",
//     AuthorisedQty: 3.0,
//     ReceivedQty: 3.0,
//     BalanceQty: 0.0,
//     ReviewedQty: 3.0,
//     VettedQty: 3.0,
//     RecommendedQty: 3.0,
//     DateFromWhichHeld: null,
//     AuthorityRef: "WOS-24",
//     AuthorityDate: "2026-01-29T00:00:00",
//     Justification: "Initial issue",
//     Price: null,
//     TotalCost: null,
//     Remarks: null,
//     ClosedBy: null,
//     DateTimeClosed: null,
//   },
//   {
//     WOSSerial: 24,
//     WOSLineSerial: 10,
//     ItemCode: "N7110-P061123",
//     ItemDesc: "COMPUTER TABLE 48X30X30 WITH SLIDING KEYBOARD TRAY & SH",
//     ItemDeno: "NO",
//     SOS: "MO",
//     AuthorisedQty: 3.0,
//     ReceivedQty: 3.0,
//     BalanceQty: 0.0,
//     ReviewedQty: 3.0,
//     VettedQty: 3.0,
//     RecommendedQty: 3.0,
//     DateFromWhichHeld: null,
//     AuthorityRef: "WOS-24",
//     AuthorityDate: "2026-01-29T00:00:00",
//     Justification: "Initial issue",
//     Price: null,
//     TotalCost: null,
//     Remarks: null,
//     ClosedBy: null,
//     DateTimeClosed: null,
//   },
// ];
